# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../recursos/main_csvloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wndwCSVLoader(object):
    # ----------------------------------------------------------- #
    def setupUi(self, wndwCSVLoader):
        wndwCSVLoader.setObjectName("wndwCSVLoader")
        wndwCSVLoader.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wndwCSVLoader.sizePolicy().hasHeightForWidth())
        wndwCSVLoader.setSizePolicy(sizePolicy)
        wndwCSVLoader.setMinimumSize(QtCore.QSize(1024, 768))
        wndwCSVLoader.setMaximumSize(QtCore.QSize(1024, 768))
        wndwCSVLoader.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(wndwCSVLoader)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tblDados = QtWidgets.QTableWidget(self.centralwidget)
        self.tblDados.setObjectName("tblDados")
        self.tblDados.setColumnCount(0)
        self.tblDados.setRowCount(0)
        self.horizontalLayout.addWidget(self.tblDados)
        wndwCSVLoader.setCentralWidget(self.centralwidget)
        self.mnuAcoes = QtWidgets.QMenuBar(wndwCSVLoader)
        self.mnuAcoes.setGeometry(QtCore.QRect(0, 0, 1024, 30))
        self.mnuAcoes.setObjectName("mnuAcoes")
        self.menuAcoes = QtWidgets.QMenu(self.mnuAcoes)
        self.menuAcoes.setObjectName("menuAcoes")
        wndwCSVLoader.setMenuBar(self.mnuAcoes)
        self.stsInformacoes = QtWidgets.QStatusBar(wndwCSVLoader)
        self.stsInformacoes.setObjectName("stsInformacoes")
        wndwCSVLoader.setStatusBar(self.stsInformacoes)
        self.actionAbrir_arquivo = QtWidgets.QAction(wndwCSVLoader)
        self.actionAbrir_arquivo.setObjectName("actionAbrir_arquivo")
        self.actionSair = QtWidgets.QAction(wndwCSVLoader)
        self.actionSair.setObjectName("actionSair")
        self.menuAcoes.addAction(self.actionAbrir_arquivo)
        self.menuAcoes.addSeparator()
        self.menuAcoes.addAction(self.actionSair)
        self.mnuAcoes.addAction(self.menuAcoes.menuAction())

        self.retranslateUi(wndwCSVLoader)
        self.actionSair.triggered.connect(wndwCSVLoader.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wndwCSVLoader)
    # ----------------------------------------------------------- #

    # ----------------------------------------------------------- #
    def retranslateUi(self, wndwCSVLoader):
        _translate = QtCore.QCoreApplication.translate
        wndwCSVLoader.setWindowTitle(_translate("wndwCSVLoader", "CSV Loader"))
        self.menuAcoes.setTitle(_translate("wndwCSVLoader", "&Ações"))
        self.actionAbrir_arquivo.setText(_translate("wndwCSVLoader", "Abrir arquivo"))
        self.actionAbrir_arquivo.setToolTip(_translate("wndwCSVLoader", "Carregar um arquivo CSV"))
        self.actionAbrir_arquivo.setShortcut(_translate("wndwCSVLoader", "Ctrl+O"))
        self.actionSair.setText(_translate("wndwCSVLoader", "Sair"))
        self.actionSair.setToolTip(_translate("wndwCSVLoader", "Encerra aplicação"))
        self.actionSair.setShortcut(_translate("wndwCSVLoader", "Ctrl+Q"))
    # ----------------------------------------------------------- #